  const REDUCER_ACTIONS = {
    SET_IS_CONNECTED_TO_REMOTE_HOST : "SET_IS_CONNECTED_TO_REMOTE_HOST",
    SET_BIRKELAND_PORT : "SET_BIRKELAND_PORT",
    SET_USERNAME: "SET_USERNAME",
    SET_PASSWORD: "SET_PASSWORD",
    SET_BUSINESS_USER_ID: "SET_BUSINESS_USER_ID",
    SET_EMAIL: "SET_EMAIL",
    SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
    SET_NODE_PUBLIC_KEY: "SET_NODE_PUBLIC_KEY",
    SET_LAST_EXECUTED_OPS : "SET_LAST_EXECUTED_OPS",
    SET_LAST_RETURNED_RESULT : "SET_LAST_RETURNED_RESULT",
    SET_USER_ID : "SET_USER_ID"
  };


 
  


module.exports = {REDUCER_ACTIONS}